---
abstract: 'Wrap text fast into chunks of similar length'
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Wrap-Smart-XS
provides:
  Text::Wrap::Smart::XS:
    file: lib/Text/Wrap/Smart/XS.pm
    version: 0.06
requires:
  Carp: 0
  Params::Validate: 0
  boolean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
